### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by sandymcp** [kwilczynski/puppet-functions#2]
Rather than checking for specific container classes, you could use
```
thing.respond_to?(:empty?)
```
To check if you can call empty

**Comment by kwilczynski** [comment]
Hi @sandymcp, thank you for reaching out.

I am sure it can be an improvement, but what I am not sure is what to? Do you have an example?

Thank you in advance!

**Comment by kwilczynski** [comment]
Closing.
